[build]
publish = "__sapper__/export/"
command = "npm run build:publish"
functions = "functions/"

[template.environment]
  SITE_TITLE = "A ProgNovel App"
  BACKEND_API = "https://{api-name}.{your-account}.workers.dev/"

# [[plugins]]
#   package = "@netlify/plugin-lighthouse"
  # optional, fails build when a category is below a threshold
  # [plugins.inputs.thresholds]
  #   performance = 0.9
  #   accessibility = 0.9
  #   best-practices = 0.9
  #   seo = 0.9
  #   pwa = 0.9

# [context.production]
#   environment = { GITHUB_USER = "ProgNovel", WORKING_REPO = "prognovel-contents" }

# [context.deploy-preview.environment]
#   GITHUB_USER = "ProgNovel"
#   WORKING_REPO = "prognovel-contents"
