[build]
publish = "__sapper__/export/"
command = "npm run build"
Functions = "netlify-functions"

[template.environment]
SITE_TITLE = "Site title"
BACKEND_API = "Your Cloudflare Workers backend URL"

