[build]
publish = "__sapper__/export/"
command = "npm run build"

[functions]
directory = "functions-netlify"

[template.environment]
SITE_TITLE = "Site title"
BACKEND_API = "Your Cloudflare Workers backend URL"

